package controller;

public enum ACTIONS {
DIBUJAR, ADYACENCIA,GUARDARGRILLA,GUARDAR_DISTANCIAS,GENERAR_MATRIZ,DISTANCIAS,ADD_CIRCULO,REMOVER,CONECTAR,GUARDAR_GRAFO,NUEVO_GRAFO,ALGORITMO_PRIM,HOLA;
}
